/**
 * Public company career boards we pull from. These are the same ATS JSON
 * endpoints companies already publish for their own sites — no LinkedIn /
 * Indeed scraping, no Firecrawl key required.
 *
 * Tokens that 404 are skipped at crawl time; keep this list easy to extend.
 */

export type BoardKind = "greenhouse" | "lever" | "ashby";

export interface Board {
    kind: BoardKind;
    token: string;
    company?: string;
}

export const BOARDS: Board[] = [
    // Greenhouse
    { kind: "greenhouse", token: "stripe", company: "Stripe" },
    { kind: "greenhouse", token: "airbnb", company: "Airbnb" },
    { kind: "greenhouse", token: "coinbase", company: "Coinbase" },
    { kind: "greenhouse", token: "discord", company: "Discord" },
    { kind: "greenhouse", token: "figma", company: "Figma" },
    { kind: "greenhouse", token: "databricks", company: "Databricks" },
    { kind: "greenhouse", token: "cloudflare", company: "Cloudflare" },
    { kind: "greenhouse", token: "gitlab", company: "GitLab" },
    { kind: "greenhouse", token: "reddit", company: "Reddit" },
    { kind: "greenhouse", token: "dropbox", company: "Dropbox" },
    { kind: "greenhouse", token: "instacart", company: "Instacart" },
    { kind: "greenhouse", token: "doordash", company: "DoorDash" },
    { kind: "greenhouse", token: "robinhood", company: "Robinhood" },
    { kind: "greenhouse", token: "pinterest", company: "Pinterest" },
    { kind: "greenhouse", token: "snowflake", company: "Snowflake" },
    { kind: "greenhouse", token: "datadog", company: "Datadog" },
    { kind: "greenhouse", token: "mongodb", company: "MongoDB" },
    { kind: "greenhouse", token: "hashicorp", company: "HashiCorp" },
    { kind: "greenhouse", token: "elastic", company: "Elastic" },
    { kind: "greenhouse", token: "atlassian", company: "Atlassian" },
    { kind: "greenhouse", token: "shopify", company: "Shopify" },
    { kind: "greenhouse", token: "twilio", company: "Twilio" },
    { kind: "greenhouse", token: "plaid", company: "Plaid" },
    { kind: "greenhouse", token: "airtable", company: "Airtable" },
    { kind: "greenhouse", token: "asana", company: "Asana" },
    { kind: "greenhouse", token: "boxinc", company: "Box" },
    { kind: "greenhouse", token: "coursera", company: "Coursera" },
    { kind: "greenhouse", token: "duolingo", company: "Duolingo" },
    { kind: "greenhouse", token: "etsy", company: "Etsy" },
    { kind: "greenhouse", token: "github", company: "GitHub" },
    { kind: "greenhouse", token: "grammarly", company: "Grammarly" },
    { kind: "greenhouse", token: "hubspot", company: "HubSpot" },
    { kind: "greenhouse", token: "intercom", company: "Intercom" },
    { kind: "greenhouse", token: "lyft", company: "Lyft" },
    { kind: "greenhouse", token: "mozilla", company: "Mozilla" },
    { kind: "greenhouse", token: "okta", company: "Okta" },
    { kind: "greenhouse", token: "spotify", company: "Spotify" },
    { kind: "greenhouse", token: "zendesk", company: "Zendesk" },
    { kind: "greenhouse", token: "zoom", company: "Zoom" },
    { kind: "greenhouse", token: "cloudkitchens", company: "CloudKitchens" },
    { kind: "greenhouse", token: "brex", company: "Brex" },
    { kind: "greenhouse", token: "ramp", company: "Ramp" },
    { kind: "greenhouse", token: "rippling", company: "Rippling" },
    { kind: "greenhouse", token: "gusto", company: "Gusto" },
    { kind: "greenhouse", token: "flexport", company: "Flexport" },
    { kind: "greenhouse", token: "cruise", company: "Cruise" },
    { kind: "greenhouse", token: "andurilindustries", company: "Anduril" },
    { kind: "greenhouse", token: "anthropic", company: "Anthropic" },
    { kind: "greenhouse", token: "scaleai", company: "Scale AI" },
    { kind: "greenhouse", token: "huggingface", company: "Hugging Face" },
    { kind: "greenhouse", token: "replicate", company: "Replicate" },
    { kind: "greenhouse", token: "togetherai", company: "Together AI" },
    { kind: "greenhouse", token: "sentry", company: "Sentry" },
    { kind: "greenhouse", token: "posthog", company: "PostHog" },
    { kind: "greenhouse", token: "vercel", company: "Vercel" },
    { kind: "greenhouse", token: "supabase", company: "Supabase" },
    { kind: "greenhouse", token: "linear", company: "Linear" },
    { kind: "greenhouse", token: "notion", company: "Notion" },
    { kind: "greenhouse", token: "canva", company: "Canva" },
    { kind: "greenhouse", token: "wise", company: "Wise" },
    { kind: "greenhouse", token: "revolut", company: "Revolut" },
    { kind: "greenhouse", token: "nubank", company: "Nubank" },
    { kind: "greenhouse", token: "razorpay", company: "Razorpay" },
    { kind: "greenhouse", token: "phonepe", company: "PhonePe" },
    { kind: "greenhouse", token: "zerodha", company: "Zerodha" },
    { kind: "greenhouse", token: "freshworks", company: "Freshworks" },
    { kind: "greenhouse", token: "zoho", company: "Zoho" },
    { kind: "greenhouse", token: "browserstack", company: "BrowserStack" },
    { kind: "greenhouse", token: "postman", company: "Postman" },
    { kind: "greenhouse", token: "cred", company: "CRED" },
    { kind: "greenhouse", token: "meesho", company: "Meesho" },
    { kind: "greenhouse", token: "swiggy", company: "Swiggy" },
    { kind: "greenhouse", token: "zomato", company: "Zomato" },
    { kind: "greenhouse", token: "flipkart", company: "Flipkart" },
    { kind: "greenhouse", token: "paytm", company: "Paytm" },
    { kind: "greenhouse", token: "thoughtworks", company: "Thoughtworks" },
    { kind: "greenhouse", token: "infosys", company: "Infosys" },
    // Lever
    { kind: "lever", token: "palantir", company: "Palantir" },
    { kind: "lever", token: "anduril", company: "Anduril" },
    { kind: "lever", token: "netflix", company: "Netflix" },
    { kind: "lever", token: "spotify", company: "Spotify" },
    { kind: "lever", token: "twitch", company: "Twitch" },
    { kind: "lever", token: "uber", company: "Uber" },
    { kind: "lever", token: "lyft", company: "Lyft" },
    { kind: "lever", token: "shopify", company: "Shopify" },
    { kind: "lever", token: "reddit", company: "Reddit" },
    { kind: "lever", token: "duolingo", company: "Duolingo" },
    { kind: "lever", token: "wealthfront", company: "Wealthfront" },
    { kind: "lever", token: "affirm", company: "Affirm" },
    { kind: "lever", token: "mixpanel", company: "Mixpanel" },
    { kind: "lever", token: "segment", company: "Twilio Segment" },
    { kind: "lever", token: "better", company: "Better.com" },
    { kind: "lever", token: "creditkarma", company: "Credit Karma" },
    { kind: "lever", token: "quora", company: "Quora" },
    { kind: "lever", token: "sourceress", company: "Sourceress" },
    // Ashby
    { kind: "ashby", token: "openai", company: "OpenAI" },
    { kind: "ashby", token: "anthropic", company: "Anthropic" },
    { kind: "ashby", token: "notion", company: "Notion" },
    { kind: "ashby", token: "linear", company: "Linear" },
    { kind: "ashby", token: "vercel", company: "Vercel" },
    { kind: "ashby", token: "ramp", company: "Ramp" },
    { kind: "ashby", token: "mercury", company: "Mercury" },
    { kind: "ashby", token: "cursor", company: "Cursor" },
    { kind: "ashby", token: "perplexity", company: "Perplexity" },
    { kind: "ashby", token: "xai", company: "xAI" },
    { kind: "ashby", token: "anysphere", company: "Anysphere" },
    { kind: "ashby", token: "browserbase", company: "Browserbase" },
    { kind: "ashby", token: "resend", company: "Resend" },
    { kind: "ashby", token: "supabase", company: "Supabase" },
    { kind: "ashby", token: "convex", company: "Convex" },
    { kind: "ashby", token: "clerk", company: "Clerk" },
    { kind: "ashby", token: "plain", company: "Plain" },
    { kind: "ashby", token: "parallel", company: "Parallel" },
];
